# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicStreaming' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicStreaming
  pod 'SwiftyJSON'
 pod 'MarqueeLabel', '~> 3.0'
end
